In [2]:
import numpy as np
import pandas as pd

In [55]:
df1=pd.read_csv("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20150101_20151231_pre.csv", encoding="euc-kr")
#df2=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20160101_20161231.xlsx", encoding="euc-kr")
#df3=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20170101_20171231.xlsx", encoding="euc-kr")
#df4=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20180101_20181231.xlsx", encoding="euc-kr")

C:\Users\minkyu\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
df1

,age(before),age(after),careAddr,careNm,colorCd,happenDt,happenPlace,kindCd,neuterYn,noticeEdt,noticeNo,noticeSdt,orgNm,processState,sexCd,weight(before),weight(after),두마리이상
0,6개월추정(년생),0.00,충청남도 공주시 번영1로 54 (신관동),강북동물병원,흰갈색,20151231,중동 사거리,[개] 믹스견,N,20160121,충남-공주-2016-00016,20160111,충청남도 공주시,종료(안락사),F,6(Kg),6.00,NaN
1,4살추정(년생),4.00,"전라남도 순천시 중앙로 3-1 (저전동, 대한동물사랑협회)",대한동물사랑협회,흰색,20151231,팔마체육관앞도로,[개] 말티즈,N,20160114,전남-순천-2016-00009,20160107,전라남도 순천시,종료(기증),M,3.5(Kg),3.50,NaN
2,5년(년생),5.00,인천광역시 계양구 다남동 35-8,인천광역시 수의사회,검/흰,20151231,용현동195-15 대학노래방,[개] 믹스견,U,20160118,인천-남구-2016-00011,20160107,인천광역시 미추홀구,종료(방사),F,5(Kg),5.00,NaN
3,5살(년생),5.00,경상북도 칠곡군 석적읍 포망로 341 (석적읍),칠곡유기동물보호센터,갈색,20151231,가산면 학상 레미콘 앞,[개] 믹스견,U,20160118,경북-칠곡-2016-00001,20160106,경상북도 칠곡군,종료(입양),M,6(Kg),6.00,NaN
4,1(년생),1.00,"전라북도 고창군 고창읍 보릿골로 138 (고창읍, 한사랑동물병원)",한사랑동물병원,갈색,20151231,고수면 월계마을,[개] 믹스견,N,20160115,전북-고창-2016-00001,20160105,전라북도 고창군,종료(안락사),M,4(Kg),4.00,NaN
5,3살추정(년생),3.00,충청남도 서산시 호수공원12로 13 (예천동),답21동물병원,흰색 갈색 검정색,20151231,읍내동 매력it개 앞,[개] 믹스견,N,20160115,충남-서산-2016-00001,20160105,충청남도 서산시,종료(안락사),F,4.50(Kg),4.50,NaN
6,1살추정(년생),1.00,강원도 춘천시 신북읍 유포리 619-9,춘천시 동물보호센터,흰색,20151231,후평동 대진폐차장 앞,[개] 믹스견,U,20160115,강원-춘천-2016-00001,20160105,강원도 춘천시,종료(입양),M,3.00(Kg),3.00,NaN
7,7살추정(년생),7.00,경기도 양주시 남면 감악산로 63-37 (남면),한국동물구조관리협회,흰/검,20151231,백석읍 가야아파트 인근,[개] 알라스칸 말라뮤트,N,20160115,경기-양주-2016-00001,20160105,경기도 양주시,종료(안락사),M,46.0(Kg),46.00,NaN
8,2년(년생),2.00,부산광역시 해운대구 송정동 81-5,누리동물병원,황+흰색,20151231,부산광역시 기장군 정관읍 매학리 520-5,[개] 믹스견,N,20160115,부산-기장-2016-00006,20160105,부산광역시 기장군,종료(안락사),M,4.3(Kg),4.30,NaN
9,3년(년생),3.00,서울특별시 마포구 연남동 227-2,연남동물병원,갈색,20151231,상암월드컵8단지 주차장,[고양이] 고양이,N,20160115,서울-마포-2016-00001,20160105,서울특별시 마포구,종료(자연사),F,5(Kg),5.00,NaN
10,3개월추정(년생),0.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정/갈색,20151231,제주시 연동 그린마트,[고양이] 고양이,U,20160114,제주-제주-2016-00018,20160104,제주특별자치도,종료(입양),F,0.6(Kg),0.60,NaN
11,2개월추정(년생),0.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정/갈색,20151231,제주시 연동대림1차 아파트 관리사무소,[고양이] 고양이,U,20160114,제주-제주-2016-00017,20160104,제주특별자치도,종료(자연사),F,0.3(Kg),0.30,NaN
12,2살추정(년생),2.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,갈색/검정,20151231,제주시 연동지구대,[고양이] 고양이,U,20160114,제주-제주-2016-00016,20160104,제주특별자치도,종료(자연사),F,2.5(Kg),2.50,NaN
13,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 애월읍사무소,[개] 믹스견,U,20160114,제주-제주-2016-00015,20160104,제주특별자치도,종료(안락사),M,13(Kg),13.00,NaN
14,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,갈색,20151231,제주시 애월읍사무소,[개] 믹스견,U,20160114,제주-제주-2016-00014,20160104,제주특별자치도,종료(자연사),F,25(Kg),25.00,NaN
15,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정,20151231,제주시 애월읍사무소,[개] 믹스견,U,20160114,제주-제주-2016-00013,20160104,제주특별자치도,종료(자연사),F,23(Kg),23.00,NaN
16,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정,20151231,제주시 해안동가정집,[개] 믹스견,U,20160114,제주-제주-2016-00012,20160104,제주특별자치도,종료(자연사),M,15(Kg),15.00,NaN
17,2살추정(년생),2.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 영주고등학교,[개] 믹스견,U,20160114,제주-제주-2016-00011,20160104,제주특별자치도,종료(안락사),M,11(Kg),11.00,NaN
18,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 연동주택 인근,[개] 믹스견,U,20160114,제주-제주-2016-00010,20160104,제주특별자치도,종료(자연사),F,5(Kg),5.00,NaN
19,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 한림읍사무소,[개] 말티즈,U,20160114,제주-제주-2016-00009,20160104,제주특별자치도,종료(자연사),M,3.5(Kg),3.50,NaN
20,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색/갈색,20151231,제주시 한림읍사무소,[개] 믹스견,U,20160114,제주-제주-2016-00008,20160104,제주특별자치도,종료(자연사),M,13(Kg),13.00,NaN
21,2살추정(년생),2.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 한경면사무소,[개] 그레이트 피레니즈,U,20160114,제주-제주-2016-00007,20160104,제주특별자치도,종료(자연사),M,30(Kg),30.00,NaN
22,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색/갈색,20151231,제주시 애월읍사무소,[개] 믹스견,U,20160114,제주-제주-2016-00006,20160104,제주특별자치도,종료(자연사),M,15(Kg),15.00,NaN
23,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,제주시 신촌리 1586,[개] 믹스견,U,20160114,제주-제주-2016-00005,20160104,제주특별자치도,종료(자연사),F,12(Kg),12.00,NaN
24,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정,20151231,제주시 시외버스터미널,[개] 푸들,U,20160114,제주-제주-2016-00004,20160104,제주특별자치도,종료(입양),F,3(Kg),3.00,NaN
25,5개월추정(년생),0.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,검정,20151231,서귀포시 강정동,[개] 믹스견,U,20160114,제주-제주-2016-00003,20160104,제주특별자치도,종료(입양),M,6.5(Kg),6.50,NaN
26,3살추정(년생),3.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,서귀포시 상모리 왕손가든 옆,[개] 믹스견,U,20160114,제주-제주-2016-00002,20160104,제주특별자치도,종료(안락사),M,17(Kg),17.00,NaN
27,1살추정(년생),1.00,제주특별자치도 제주시 첨단동길 184-14 (용강동),제주유기동물보호센터,흰색,20151231,서귀포시 남원리,[개] 믹스견,U,20160114,제주-제주-2016-00001,20160104,제주특별자치도,종료(자연사),F,15(Kg),15.00,NaN
28,7살(년생),7.00,부산광역시 강서구 군라2길 206 (대저2동),부산동물보호센터,연갈색,20151231,어방동 하이마트,[개] 믹스견,N,20160114,경남-김해-2016-00001,20160104,경상남도 김해시,종료(입양),F,7.5(Kg),7.50,NaN
29,2~3세(년생),3.00,경상북도 포항시 북구 흥해읍 덕장리 산67-2,한국동물테마파크,흰색,20151231,포항시 북구 흥해읍,[개] 진도견,U,20160114,경북-포항-2016-00010,20160104,경상북도 포항시,종료(자연사),F,20(Kg),20.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80426,8년(년생),8.00,서울특별시 양천구 목동 657번지 16호,강현림 동물병원,흰색,20150101,신월4동길성아파트복도 (다음1-3),[개] 포메라니안,N,20150112,서울-양천-2015-00001,20150102,서울특별시 양천구,종료(반환),F,3(Kg),3.00,NaN
80427,4개월(년생),0.00,서울특별시 양천구 목동 657번지 16호,강현림 동물병원,흰/검정,20150101,신정7동계남초등학교앞(다음1-2),[고양이] 고양이,N,20150112,서울-양천-2015-00005,20150102,서울특별시 양천구,종료(자연사),M,1(Kg),1.00,NaN
80428,11년(년생),11.00,서울특별시 양천구 목동 657번지 16호,강현림 동물병원,흰/갈,20150101,신정7동봉영중학교앞 (다음1-1),[개] 시츄,N,20150112,서울-양천-2015-00004,20150102,서울특별시 양천구,종료(반환),F,3.6(Kg),3.60,NaN
80429,7살 추정(년생),7.00,서울특별시 용산구 이촌동 300-23,이상윤동물병원,white and black,20150101,용산구 소월로 40길 57 인근,[고양이] 고양이,N,20150112,서울-용산-2015-00003,20150102,서울특별시 용산구,종료(자연사),M,4(Kg),4.00,NaN
80430,4살추정(년생),4.00,서울특별시 용산구 이촌동 300-23,이상윤동물병원,흰색,20150101,이촌아파트 중간 도로옆,[개] 말티즈,N,20150112,서울-용산-2015-00002,20150102,서울특별시 용산구,종료(반환),M,5.10(Kg),5.10,NaN
80431,1년(년생),1.00,"경상남도 통영시 무전4길 10 (무전동, 주영에이스빌4차) 115호",세종동물병원,흰색,20150101,한진로즈힐 앞,[개] 푸들,N,20150112,경남-통영-2015-00003,20150101,경상남도 통영시,종료(입양),F,3(Kg),3.00,NaN
80432,3년(년생),3.00,"경상남도 통영시 무전4길 10 (무전동, 주영에이스빌4차) 115호",세종동물병원,흰색,20150101,도천아파트 앞,[개] 말티즈,N,20150112,경남-통영-2015-00002,20150101,경상남도 통영시,종료(입양),F,1.7(Kg),1.70,NaN
80433,5년(년생),5.00,"경상남도 통영시 무전4길 10 (무전동, 주영에이스빌4차) 115호",세종동물병원,흰색,20150101,도천아파트 앞,[개] 말티즈,N,20150112,경남-통영-2015-00001,20150101,경상남도 통영시,종료(입양),F,2.8(Kg),2.80,NaN
80434,4달(년생),0.00,전라북도 전주시 완산구 경원동1가 3-10,동부동물병원,살구색,20150101,이브애견앞,[개] 푸들,N,20150112,전북-전주-2015-00002,20150101,전라북도 전주시,종료(입양),M,1.2(Kg),1.20,NaN
80435,1살추정(년생),1.00,경기도 파주시 가재울로94번길 27 (목동동),금쪽같은,갈색+흰색,20150101,한울마을 407동 4층복도,[기타축종] 햄스터(기니피그),N,20150111,경기-파주-2015-00001,20150101,경기도 파주시,종료(자연사),F,0.36(Kg),0.36,NaN
80436,5살추정(년생),5.00,경기도 용인시 처인구 백암면 백암로185번길 46 (백암리 436-1),마리동물의료센터,갈색,20150101,양지면 제일리 139-1,[개] 골든 리트리버,N,20150112,경기-용인-2015-00005,20150101,경기도 용인시,종료(입양),F,18.00(Kg),18.00,NaN
80437,8세추정(년생),8.00,경기도 안산시 상록구 청곡길 50 (부곡동) 한국야생동물보호협회,한국야생동물보호협회,백,20150101,하상동 378-2 부근,[개] 말티즈,Y,20150113,경기-시흥-2015-00002,20150101,경기도 시흥시,종료(입양),M,3(Kg),3.00,NaN
80438,7세추정(년생),7.00,경기도 안산시 상록구 청곡길 50 (부곡동) 안산시 상록구 부곡동 231-5,(사)한동보,갈,20150101,고잔동 614-12 부근,[개] 푸들,N,20150111,경기-안산-2015-00001,20150101,경기도 안산시,종료(입양),M,5(Kg),5.00,NaN
80439,2살추정(년생),2.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,야막안길 53-38,[개] 믹스견,U,20150112,경기-평택-2015-00015,20150101,경기도 평택시,종료(안락사),F,5.7(Kg),5.70,NaN
80440,6살추정(년생),6.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,갈색,20150101,야막리 252-1,[개] 믹스견,N,20150112,경기-평택-2015-00014,20150101,경기도 평택시,종료(안락사),F,23(Kg),23.00,NaN
80441,5살추정(년생),5.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,진위 119,[고양이] 고양이,N,20150112,경기-평택-2015-00013,20150101,경기도 평택시,종료(자연사),M,3.3(Kg),3.30,NaN
80442,0.3살추정(년생),0.30,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,안중리 교회,[개] 믹스견,N,20150112,경기-평택-2015-00012,20150101,경기도 평택시,종료(자연사),F,1.8(Kg),1.80,NaN
80443,0.3살추정(년생),0.30,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,야막리 89-1,[개] 믹스견,N,20150112,경기-평택-2015-00011,20150101,경기도 평택시,종료(안락사),M,2.5(Kg),2.50,NaN
80444,0.3살추정(년생),0.30,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,야막리 89-1,[개] 믹스견,N,20150112,경기-평택-2015-00010,20150101,경기도 평택시,종료(안락사),M,3(Kg),3.00,NaN
80445,6살추정(년생),6.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,갈색,20150101,원정리 69-11,[개] 믹스견,U,20150112,경기-평택-2015-00009,20150101,경기도 평택시,종료(입양),M,25(Kg),25.00,NaN
80446,0.54추정(년생),0.54,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,기타,20150101,옥길리 부영@,[고양이] 고양이,N,20150112,경기-평택-2015-00008,20150101,경기도 평택시,종료(입양),F,0.8(Kg),0.80,NaN
80447,10(년생),10.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,갈색,20150101,비전동 성동초교,[개] 믹스견,U,20150112,경기-평택-2015-00007,20150101,경기도 평택시,종료(안락사),F,2(Kg),2.00,NaN
80448,1살추정(년생),1.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,기타,20150101,송탄 구조대,[개] 믹스견,N,20150112,경기-평택-2015-00006,20150101,경기도 평택시,종료(안락사),F,6(Kg),6.00,NaN
80449,1살추정(년생),1.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,기타,20150101,지산동 송북초교,[개] 믹스견,N,20150112,경기-평택-2015-00005,20150101,경기도 평택시,종료(안락사),F,4(Kg),4.00,NaN
80450,5(년생),5.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,갈색,20150101,도일동 867,[개] 믹스견,N,20150112,경기-평택-2015-00004,20150101,경기도 평택시,종료(안락사),F,9(Kg),9.00,NaN
80451,2살추정(년생),2.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,흰색,20150101,팽성파출소,[개] 스피츠,N,20150112,경기-평택-2015-00003,20150101,경기도 평택시,종료(입양),M,8(Kg),8.00,NaN
80452,1살추정(년생),1.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,기타,20150101,신장동 근린공원,[개] 믹스견,N,20150112,경기-평택-2015-00002,20150101,경기도 평택시,종료(반환),F,27(Kg),27.00,NaN
80453,3살추정(년생),3.00,경기도 평택시 진위면 야막길 88-37 (진위면),평택시유기동물보호소,갈색,20150101,지산동 하이웨이,[개] 푸들,N,20150112,경기-평택-2015-00001,20150101,경기도 평택시,종료(안락사),M,5.7(Kg),5.70,NaN
80454,12세 추정(년생),12.00,"경기도 성남시 분당구 불정로 266 (수내동, 유신제일조합)",펫토피아동물병원,갈색 백색,20150101,태평동 3693-8,[개] 믹스견,U,20150112,경기-성남-2015-00001,20150101,경기도 성남시,종료(반환),F,5.5(Kg),5.50,NaN
80455,2달추정(년생),0.00,경기도 수원시 팔달구 인계동 1135-7,정동물병원,흑백,20150101,권선동 공원,[고양이] 고양이,N,20150108,경기-수원-2015-00001,20150101,경기도 수원시,종료(입양),M,0.2(Kg),0.20,NaN

In [56]:
#all_df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10])
#cs=all_df.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm'],axis=1)
df1=df1.drop(['두마리이상'],axis=1)
#df2=df2.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)
#df3=df3.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)
#df4=df4.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)

In [57]:
df1[['processState','sexCd','neuterYn']].isnull().sum()

processState    0
sexCd           0
neuterYn        0
dtype: int64

In [58]:
#df2[['processState','sexCd','neuterYn']].isnull().sum()

NameError: name 'df2' is not defined

In [59]:
#df3[['processState','sexCd','neuterYn']].isnull().sum()

NameError: name 'df3' is not defined

In [62]:
#df4[['processState','sexCd','neuterYn']].isnull().sum()

In [64]:
df1['processState'].value_counts()

종료(입양)     27764
종료(자연사)    19328
종료(안락사)    17001
종료(반환)     11936
보호중         1455
종료(기증)      1366
종료(방사)       856
종료(미포획)       39
Name: processState, dtype: int64

### (processState, sexCd, neuterYn) 전처리(레이블링, column화, one-hot 코딩)

In [65]:
df1.loc[df1['processState']=='보호중','processState'] ='C'# 보호중
df1.loc[df1['processState']=='종료(입양)','processState']='A'
df1.loc[df1['processState']=='종료(기증)','processState']='A'
df1.loc[df1['processState']=='종료(자연사)','processState']='D'
df1.loc[df1['processState']=='종료(안락사)','processState']='D'
df1.loc[df1['processState']=='종료(반환)','processState']='R'
df1.loc[df1['processState']=='종료(방사)','processState']='E'
df1.loc[df1['processState']=='종료(미포획)','processState']='E'

In [66]:
# 데이터에서 값제거 코드
#df1 = df1[df1.processState!='종료(방사)']

In [67]:
df1['processState_C']=df1['processState']=='C' #보호중
df1['processState_A']=df1['processState']=='A' #입양+기증
df1['processState_D']=df1['processState']=='D' #자연사+안락사
df1['processState_R']=df1['processState']=='R' #반환
df1['processState_E']=df1['processState']=='E' #미포획+방사
df1[['processState','processState_C','processState_A','processState_D','processState_R','processState_E']].head(20)

,processState,processState_C,processState_A,processState_D,processState_R,processState_E
0,D,False,False,True,False,False
1,A,False,True,False,False,False
2,E,False,False,False,False,True
3,A,False,True,False,False,False
4,D,False,False,True,False,False
5,D,False,False,True,False,False
6,A,False,True,False,False,False
7,D,False,False,True,False,False
8,D,False,False,True,False,False
9,D,False,False,True,False,False
10,A,False,True,False,False,False
11,D,False,False,True,False,False
12,D,False,False,True,False,False
13,D,False,False,True,False,False
14,D,False,False,True,False,False
15,D,False,False,True,False,False
16,D,False,False,True,False,False
17,D,False,False,True,False,False
18,D,False,False,True,False,False
19,D,False,False,True,False,False

### 성별( M=남, F=여자, Q=미상)

In [68]:
df1['sexCd_M']=df1['sexCd']=='M'
df1['sexCd_F']=df1['sexCd']=='F'
df1['sexCd_Q']=df1['sexCd']=='Q'
df1[['sexCd','sexCd_M','sexCd_F','sexCd_Q']].head(30)

   sexCd  sexCd_M  sexCd_F  sexCd_Q
0      F    False     True    False
1      M     True    False    False
2      F    False     True    False
3      M     True    False    False
4      M     True    False    False
5      F    False     True    False
6      M     True    False    False
7      M     True    False    False
8      M     True    False    False
9      F    False     True    False
10     F    False     True    False
11     F    False     True    False
12     F    False     True    False
13     M     True    False    False
14     F    False     True    False
15     F    False     True    False
16     M     True    False    False
17     M     True    False    False
18     F    False     True    False
19     M     True    False    False
20     M     True    False    False
21     M     True    False    False
22     M     True    False    False
23     F    False     True    False
24     F    False     True    False
25     M     True    False    False
26     M     True    False    False
27     F    False     True    False
28     F    False     True    False
29     F    False     True    False

### 중성화여부 (Y=중성화, N=중성화X, U=미확인)

In [69]:
df1['neuterYn_Y']=df1['neuterYn']=='Y'
df1['neuterYn_N']=df1['neuterYn']=='N'
df1['neuterYn_U']=df1['neuterYn']=='U'
df1[['neuterYn','neuterYn_Y','neuterYn_N','neuterYn_U']].head(20)

   neuterYn  neuterYn_Y  neuterYn_N  neuterYn_U
0         N       False        True       False
1         N       False        True       False
2         U       False       False        True
3         U       False       False        True
4         N       False        True       False
5         N       False        True       False
6         U       False       False        True
7         N       False        True       False
8         N       False        True       False
9         N       False        True       False
10        U       False       False        True
11        U       False       False        True
12        U       False       False        True
13        U       False       False        True
14        U       False       False        True
15        U       False       False        True
16        U       False       False        True
17        U       False       False        True
18        U       False       False        True
19        U       False       False        True

### 보호장소

In [108]:
dfh1=df1['careNm'].str.contains('병원|의료센터|메디컬|클리닉|의료원') #메디컬(715)+의료(91)+의료(23408)
dfh2=df1['careNm'].str.contains('보호소|보호센터|리본센터') #보호소(18387)+센터(18413)
dfh3=df1['careNm'].str.contains('군청|시청') #군청(54)+시청(24)
dfh4=df1['careNm'].str.contains('수의사회') #수의사회(2443)
dfh5=df1['careNm'].str.contains('한동보|협회|보호협' ) #한동보(1115)+동물협회(10806)
dfh6=df1['careNm'].str.contains('병원|의료|메디컬|클리닉|보호소|보호센터|리본센터|군청|시청|수의사회|한동보|협회|보호협|의료원')==False

In [109]:
df1['careNm_ETC']=dfh6 #밑에 컬럼속성들을 제외한 속성
df1['careNm_H']=dfh1 # 병원,의료센터,메디컬,클리닉,의료원
df1['careNm_C']=dfh2 # 보호소,보호센터,리본센터
df1['careNm_O']=dfh3 # 군청, 시청
df1['careNm_AD']=dfh4 # 수의사회
df1['careNm_CM']=dfh5 # 한동보,동물협회

In [110]:
df1[['careNm','careNm_ETC','careNm_H','careNm_C','careNm_O','careNm_AD','careNm_CM']]

,careNm,careNm_ETC,careNm_H,careNm_C,careNm_O,careNm_AD,careNm_CM
0,강북동물병원,False,True,False,False,False,False
1,대한동물사랑협회,False,False,False,False,False,True
2,인천광역시 수의사회,False,False,False,False,True,False
3,칠곡유기동물보호센터,False,False,True,False,False,False
4,한사랑동물병원,False,True,False,False,False,False
5,답21동물병원,False,True,False,False,False,False
6,춘천시 동물보호센터,False,False,True,False,False,False
7,한국동물구조관리협회,False,False,False,False,False,True
8,누리동물병원,False,True,False,False,False,False
9,연남동물병원,False,True,False,False,False,False
10,제주유기동물보호센터,False,False,True,False,False,False
11,제주유기동물보호센터,False,False,True,False,False,False
12,제주유기동물보호센터,False,False,True,False,False,False
13,제주유기동물보호센터,False,False,True,False,False,False
14,제주유기동물보호센터,False,False,True,False,False,False
15,제주유기동물보호센터,False,False,True,False,False,False
16,제주유기동물보호센터,False,False,True,False,False,False
17,제주유기동물보호센터,False,False,True,False,False,False
18,제주유기동물보호센터,False,False,True,False,False,False
19,제주유기동물보호센터,False,False,True,False,False,False
20,제주유기동물보호센터,False,False,True,False,False,False
21,제주유기동물보호센터,False,False,True,False,False,False
22,제주유기동물보호센터,False,False,True,False,False,False
23,제주유기동물보호센터,False,False,True,False,False,False
24,제주유기동물보호센터,False,False,True,False,False,False
25,제주유기동물보호센터,False,False,True,False,False,False
26,제주유기동물보호센터,False,False,True,False,False,False
27,제주유기동물보호센터,False,False,True,False,False,False
28,부산동물보호센터,False,False,True,False,False,False
29,한국동물테마파크,True,False,False,False,False,False
...,...,...,...,...,...,...,...
79715,강현림 동물병원,False,True,False,False,False,False
79716,강현림 동물병원,False,True,False,False,False,False
79717,강현림 동물병원,False,True,False,False,False,False
79718,이상윤동물병원,False,True,False,False,False,False
79719,이상윤동물병원,False,True,False,False,False,False
79720,세종동물병원,False,True,False,False,False,False
79721,세종동물병원,False,True,False,False,False,False
79722,세종동물병원,False,True,False,False,False,False
79723,동부동물병원,False,True,False,False,False,False
79724,금쪽같은,True,False,False,False,False,False
79725,마리동물의료센터,False,True,False,False,False,False
79726,한국야생동물보호협회,False,False,False,False,False,True
79727,(사)한동보,False,False,False,False,False,True
79728,평택시유기동물보호소,False,False,True,False,False,False
79729,평택시유기동물보호소,False,False,True,False,False,False
79730,평택시유기동물보호소,False,False,True,False,False,False
79731,평택시유기동물보호소,False,False,True,False,False,False
79732,평택시유기동물보호소,False,False,True,False,False,False
79733,평택시유기동물보호소,False,False,True,False,False,False
79734,평택시유기동물보호소,False,False,True,False,False,False
79735,평택시유기동물보호소,False,False,True,False,False,False
79736,평택시유기동물보호소,False,False,True,False,False,False
79737,평택시유기동물보호소,False,False,True,False,False,False
79738,평택시유기동물보호소,False,False,True,False,False,False
79739,평택시유기동물보호소,False,False,True,False,False,False
79740,평택시유기동물보호소,False,False,True,False,False,False
79741,평택시유기동물보호소,False,False,True,False,False,False
79742,평택시유기동물보호소,False,False,True,False,False,False
79743,펫토피아동물병원,False,True,False,False,False,False
79744,정동물병원,False,True,False,False,False,False

In [111]:
df1.to_csv('test_df1-1.csv',encoding='euc-kr')

In [74]:
# df1['orgNm'][df1['orgNm'].str.contains('서울특별시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경기도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('강원도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경상남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경상북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('전라남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('전라북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('충청남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('충청북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('울산광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('부산광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('대전광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('제주특별자치도')==True]
#df1['orgNm'].unique()

In [75]:
df1['orgNm'].str.contains('서울특별시').sum()

8859

In [76]:
df1['orgNm'].str.contains('경기도').sum()

19300

In [77]:
df1['orgNm'].str.contains('강원도').sum()

3559

In [78]:
df1['orgNm'].str.contains('경상남도').sum()

5581

In [79]:
df1['orgNm'].str.contains('경상북도').sum()

3259

In [80]:
df1['orgNm'].str.contains('전라남도').sum()

2943

In [81]:
df1['orgNm'].str.contains('전라북도').sum()

3299

In [82]:
df1['orgNm'].str.contains('충청남도').sum()

4558

In [83]:
df1['orgNm'].str.contains('충청북도').sum()

2955

In [ ]:
df1['orgNm'].str.contains('울산광역시').sum()

2986

In [85]:
df1['orgNm'].str.contains('부산광역시').sum()

6937

In [86]:
df1['orgNm'].str.contains('대전광역시').sum()

3158

In [87]:
df1['orgNm'].str.contains('제주특별자치도').sum()

1775

In [88]:
df1['orgNm'].str.contains('세종특별자치시').sum()

284

In [89]:
df1['orgNm'].str.contains('인천광역시').sum()

5195

In [90]:
df1['orgNm'].str.contains('광주광역시').sum()

1683

In [91]:
df1['orgNm'].str.contains('대구광역시').sum()

3414

### KindCd, happenDt, happenPlace, colorCd

### Kind Cd

In [92]:
df1['kindCd'].head()

0    [개] 믹스견
1    [개] 말티즈
2    [개] 믹스견
3    [개] 믹스견
4    [개] 믹스견
Name: kindCd, dtype: object

In [93]:
df1['kind'] = df1['kindCd'].str.extract('([가-힣]+)\]', expand=False) # 한글 정규식
df1['kind'].head()

0    개
1    개
2    개
3    개
4    개
Name: kind, dtype: object

In [94]:
kind_mapping = {'개': 0, '고양이':1, '기타축종':2}
df1['kind'] = df1['kind'].map(kind_mapping)

In [95]:
df1['kind'].value_counts()

0    58220
1    20602
2      923
Name: kind, dtype: int64

In [96]:
df1['breed'] = df1['kindCd'].str.split('] ').str[1]

In [97]:
df1['breed'].head()

0    믹스견
1    말티즈
2    믹스견
3    믹스견
4    믹스견
Name: breed, dtype: object

In [98]:
# breed = df1['breed'].value_counts()
# breed

### happenDt

In [113]:
df1['happenDt']

0        2015-12-31
1        2015-12-31
2        2015-12-31
3        2015-12-31
4        2015-12-31
5        2015-12-31
6        2015-12-31
7        2015-12-31
8        2015-12-31
9        2015-12-31
10       2015-12-31
11       2015-12-31
12       2015-12-31
13       2015-12-31
14       2015-12-31
15       2015-12-31
16       2015-12-31
17       2015-12-31
18       2015-12-31
19       2015-12-31
20       2015-12-31
21       2015-12-31
22       2015-12-31
23       2015-12-31
24       2015-12-31
25       2015-12-31
26       2015-12-31
27       2015-12-31
28       2015-12-31
29       2015-12-31
            ...
79715    2015-01-01
79716    2015-01-01
79717    2015-01-01
79718    2015-01-01
79719    2015-01-01
79720    2015-01-01
79721    2015-01-01
79722    2015-01-01
79723    2015-01-01
79724    2015-01-01
79725    2015-01-01
79726    2015-01-01
79727    2015-01-01
79728    2015-01-01
79729    2015-01-01
79730    2015-01-01
79731    2015-01-01
79732    2015-01-01
79733    2015-01-01
79734    2015-01-01
79735    2015-01-01
79736    2015-01-01
79737    2015-01-01
79738    2015-01-01
79739    2015-01-01
79740    2015-01-01
79741    2015-01-01
79742    2015-01-01
79743    2015-01-01
79744    2015-01-01
Name: happenDt, Length: 79745, dtype: object

In [112]:
df1['happenDt'] = pd.to_datetime(df1['happenDt'], format='%Y%m%d')
# 8자리를 날짜형식으로 바꿈

ValueError: time data '2015-12-31' does not match format '%Y%m%d' (match)

In [ ]:
df1['happenDt'].head()

In [ ]:
# df['happenWd'] = df['happenDt'].dt.dayofweekday  # 요일을 숫자로 표현함 "0 = Sunday"
df1['happenWd'] = df1['happenDt'].dt.day_name()

In [ ]:
df1['happenWd'].head()

In [ ]:
df1['happenWd'].value_counts()

In [ ]:
df1['happenMth'] = pd.DatetimeIndex(df1['happenDt']).month
# 날짜에서 '월'값을 받음

In [ ]:
df1['happenMth'].value_counts()

### weight

In [100]:
df1['weight(after)'].head()

0    6.0
1    3.5
2    5.0
3    6.0
4    4.0
Name: weight(after), dtype: float64

In [101]:
df1.loc[df1['weight(after)'] <= 3, 'size'] = '초소형'
df1.loc[(df1['weight(after)'] > 3 ) & (df1['weight(after)'] <=9 ), 'size'] = '소형'
df1.loc[(df1['weight(after)'] > 9 ) & (df1['weight(after)'] <=25 ), 'size'] = '중형'
df1.loc[df1['weight(after)'] > 25, 'size'] = '대형'

In [102]:
df1['size'].head()

0    소형
1    소형
2    소형
3    소형
4    소형
Name: size, dtype: object

In [103]:
df1.loc[df1['age(after)'] <= 1, 'age_u'] = '유견기'
df1.loc[(df1['age(after)'] > 1 ) & (df1['age(after)'] <= 9 ), 'age_u'] = '성견기'
df1.loc[df1['age(after)'] > 9, 'age_u'] = '노견기'

In [104]:
df1['age_u'].head()

0    유견기
1    성견기
2    성견기
3    성견기
4    유견기
Name: age_u, dtype: object

In [105]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'age(before)', 'age(after)', 'careAddr',
       'careNm', 'careTel', 'chargeNm', 'colorCd', 'desertionNo', 'filename',
       'happenDt', 'happenPlace', 'kindCd', 'neuterYn', 'noticeComment',
       'noticeEdt', 'noticeNo', 'noticeSdt', 'officetel', 'orgNm', 'popfile',
       'processState', 'sexCd', 'specialMark', 'weight(before)',
       'weight(after)', 'kind', 'breed', 'breed_Pre', 'happenWd', 'happenMth',
       'size', 'age_u', 'processState_C', 'processState_A', 'processState_D',
       'processState_R', 'processState_E', 'sexCd_M', 'sexCd_F', 'sexCd_Q',
       'neuterYn_Y', 'neuterYn_N', 'neuterYn_U', 'careNm_ETC', 'careNm_H',
       'careNm_C', 'careNm_O', 'careNm_AD', 'careNm_CM'],
      dtype='object')

In [107]:
df1.to_csv('lostAnimal_20150101_20151231_pre_vol1.csv',encoding='euc-kr')