In [1]:
import numpy as np
import pandas as pd

In [30]:
df1=pd.read_csv("D:\pycharmProject\BigdataProject_AbandonedAnimal\lostAnimal_20180101_20181231_vol2.csv", encoding="euc-kr")
#df2=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20160101_20161231.xlsx", encoding="euc-kr")
#df3=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20170101_20171231.xlsx", encoding="euc-kr")
#df4=pd.read_excel("D:\JupyterNotebook\project\lostAnimal_data\processing_data\lostAnimal_20180101_20181231.xlsx", encoding="euc-kr")

In [ ]:
df1

In [ ]:
#all_df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10])
#cs=all_df.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm'],axis=1)
df1=df1.drop(['두마리이상'],axis=1)
#df2=df2.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)
#df3=df3.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)
#df4=df4.drop(['Unnamed: 0','chargeNm','desertionNo','filename','noticeComment','officetel','popfile','specialMark','orgNm','careTel'],axis=1)

In [ ]:
df1[['processState','sexCd','neuterYn']].isnull().sum()

In [ ]:
#df2[['processState','sexCd','neuterYn']].isnull().sum()

In [ ]:
#df3[['processState','sexCd','neuterYn']].isnull().sum()

In [ ]:
#df4[['processState','sexCd','neuterYn']].isnull().sum()

In [ ]:
df1['processState'].value_counts()

### (processState, sexCd, neuterYn) 전처리(레이블링, column화, one-hot 코딩)

In [31]:
df1.loc[df1['processState']=='보호중','processState_Pre'] ='C'# 보호중
df1.loc[df1['processState']=='종료(입양)','processState_Pre']='A'
df1.loc[df1['processState']=='종료(기증)','processState_Pre']='A'
df1.loc[df1['processState']=='종료(자연사)','processState_Pre']='D'
df1.loc[df1['processState']=='종료(안락사)','processState_Pre']='D'
df1.loc[df1['processState']=='종료(반환)','processState_Pre']='R'
df1.loc[df1['processState']=='종료(방사)','processState_Pre']='E'
df1.loc[df1['processState']=='종료(미포획)','processState_Pre']='E'

In [ ]:
# 데이터에서 값제거 코드
#df1 = df1[df1.processState!='종료(방사)']

In [32]:
df1['processState_C']=df1['processState']=='C' #보호중
df1['processState_A']=df1['processState']=='A' #입양+기증
df1['processState_D']=df1['processState']=='D' #자연사+안락사
df1['processState_R']=df1['processState']=='R' #반환
df1['processState_E']=df1['processState']=='E' #미포획+방사
df1[['processState','processState_C','processState_A','processState_D','processState_R','processState_E']].head(20)

,processState,processState_C,processState_A,processState_D,processState_R,processState_E
0,보호중,False,False,False,False,False
1,보호중,False,False,False,False,False
2,보호중,False,False,False,False,False
3,보호중,False,False,False,False,False
4,보호중,False,False,False,False,False
5,보호중,False,False,False,False,False
6,보호중,False,False,False,False,False
7,보호중,False,False,False,False,False
8,종료(입양),False,False,False,False,False
9,보호중,False,False,False,False,False
10,보호중,False,False,False,False,False
11,보호중,False,False,False,False,False
12,보호중,False,False,False,False,False
13,보호중,False,False,False,False,False
14,보호중,False,False,False,False,False
15,보호중,False,False,False,False,False
16,보호중,False,False,False,False,False
17,보호중,False,False,False,False,False
18,보호중,False,False,False,False,False
19,보호중,False,False,False,False,False

### 성별( M=남, F=여자, Q=미상)

In [33]:
df1['sexCd_M']=df1['sexCd']=='M'
df1['sexCd_F']=df1['sexCd']=='F'
df1['sexCd_Q']=df1['sexCd']=='Q'
df1[['sexCd','sexCd_M','sexCd_F','sexCd_Q']].head(30)

   sexCd  sexCd_M  sexCd_F  sexCd_Q
0      F    False     True    False
1      M     True    False    False
2      M     True    False    False
3      F    False     True    False
4      F    False     True    False
5      F    False     True    False
6      M     True    False    False
7      F    False     True    False
8      F    False     True    False
9      M     True    False    False
10     F    False     True    False
11     M     True    False    False
12     F    False     True    False
13     M     True    False    False
14     M     True    False    False
15     M     True    False    False
16     F    False     True    False
17     F    False     True    False
18     F    False     True    False
19     M     True    False    False
20     Q    False    False     True
21     Q    False    False     True
22     M     True    False    False
23     M     True    False    False
24     Q    False    False     True
25     Q    False    False     True
26     M     True    False    False
27     M     True    False    False
28     Q    False    False     True
29     M     True    False    False

### 중성화여부 (Y=중성화, N=중성화X, U=미확인)

In [34]:
df1['neuterYn_Y']=df1['neuterYn']=='Y'
df1['neuterYn_N']=df1['neuterYn']=='N'
df1['neuterYn_U']=df1['neuterYn']=='U'
df1[['neuterYn','neuterYn_Y','neuterYn_N','neuterYn_U']].head(20)

   neuterYn  neuterYn_Y  neuterYn_N  neuterYn_U
0         N       False        True       False
1         N       False        True       False
2         N       False        True       False
3         N       False        True       False
4         N       False        True       False
5         N       False        True       False
6         N       False        True       False
7         U       False       False        True
8         N       False        True       False
9         N       False        True       False
10        U       False       False        True
11        N       False        True       False
12        N       False        True       False
13        N       False        True       False
14        N       False        True       False
15        N       False        True       False
16        N       False        True       False
17        U       False       False        True
18        N       False        True       False
19        Y        True       False       False

### 보호장소

In [35]:
dfh1=df1['careNm'].str.contains('병원|의료센터|메디컬|클리닉|의료원') #메디컬(715)+의료(91)+의료(23408)
dfh2=df1['careNm'].str.contains('보호소|보호센터|리본센터') #보호소(18387)+센터(18413)
dfh3=df1['careNm'].str.contains('군청|시청') #군청(54)+시청(24)
dfh4=df1['careNm'].str.contains('수의사회') #수의사회(2443)
dfh5=df1['careNm'].str.contains('한동보|협회|보호협' ) #한동보(1115)+동물협회(10806)
dfh6=df1['careNm'].str.contains('병원|의료|메디컬|클리닉|보호소|보호센터|리본센터|군청|시청|수의사회|한동보|협회|보호협|의료원')==False

In [36]:
df1['careNm_ETC']=dfh6 #밑에 컬럼속성들을 제외한 속성
df1['careNm_H']=dfh1 # 병원,의료센터,메디컬,클리닉,의료원
df1['careNm_C']=dfh2 # 보호소,보호센터,리본센터
df1['careNm_O']=dfh3 # 군청, 시청
df1['careNm_AD']=dfh4 # 수의사회
df1['careNm_CM']=dfh5 # 한동보,동물협회

In [37]:
df1[['careNm','careNm_ETC','careNm_H','careNm_C','careNm_O','careNm_AD','careNm_CM']]

,careNm,careNm_ETC,careNm_H,careNm_C,careNm_O,careNm_AD,careNm_CM
0,포두동물병원,False,True,False,False,False,False
1,포두동물병원,False,True,False,False,False,False
2,포두동물병원,False,True,False,False,False,False
3,포두동물병원,False,True,False,False,False,False
4,포두동물병원,False,True,False,False,False,False
5,포두동물병원,False,True,False,False,False,False
6,포두동물병원,False,True,False,False,False,False
7,당진시동물보호소,False,False,True,False,False,False
8,반려동물보호센터,False,False,True,False,False,False
9,반려동물보호센터,False,False,True,False,False,False
10,반려동물보호센터,False,False,True,False,False,False
11,반려동물보호센터,False,False,True,False,False,False
12,강아지와 고양이,True,False,False,False,False,False
13,강아지와 고양이,True,False,False,False,False,False
14,강아지와 고양이,True,False,False,False,False,False
15,강아지와 고양이,True,False,False,False,False,False
16,강아지와 고양이,True,False,False,False,False,False
17,오산시수의사회,False,False,False,False,True,False
18,24시아이동물메디컬,False,True,False,False,False,False
19,24시아이동물메디컬,False,True,False,False,False,False
20,허동물병원,False,True,False,False,False,False
21,예스동물병원,False,True,False,False,False,False
22,대구시수의사회(보경),False,False,False,False,True,False
23,대구시수의사회(보경),False,False,False,False,True,False
24,유기동물및동물보호협,False,False,False,False,False,True
25,유기동물및동물보호협,False,False,False,False,False,True
26,누리동물병원,False,True,False,False,False,False
27,유기동물및동물보호협,False,False,False,False,False,True
28,유기동물및동물보호협,False,False,False,False,False,True
29,유기동물및동물보호협,False,False,False,False,False,True
...,...,...,...,...,...,...,...
80300,남양주동물보호협회,False,False,False,False,False,True
80301,남양주동물보호협회,False,False,False,False,False,True
80302,(사)한동보,False,False,False,False,False,True
80303,(사)한동보,False,False,False,False,False,True
80304,(사)한동보,False,False,False,False,False,True
80305,(사)한동보,False,False,False,False,False,True
80306,(사)한동보,False,False,False,False,False,True
80307,(사)한동보,False,False,False,False,False,True
80308,평택시유기동물보호소,False,False,True,False,False,False
80309,평택시유기동물보호소,False,False,True,False,False,False
80310,평택시유기동물보호소,False,False,True,False,False,False
80311,평택시유기동물보호소,False,False,True,False,False,False
80312,평택시유기동물보호소,False,False,True,False,False,False
80313,평택시유기동물보호소,False,False,True,False,False,False
80314,평택시유기동물보호소,False,False,True,False,False,False
80315,한국야생동물보호협회,False,False,False,False,False,True
80316,한국야생동물보호협회,False,False,False,False,False,True
80317,한국야생동물보호협회,False,False,False,False,False,True
80318,한국야생동물보호협회,False,False,False,False,False,True
80319,24시아이동물메디컬,False,True,False,False,False,False
80320,24시아이동물메디컬,False,True,False,False,False,False
80321,24시아이동물메디컬,False,True,False,False,False,False
80322,24시아이동물메디컬,False,True,False,False,False,False
80323,한국야생동물보호협회,False,False,False,False,False,True
80324,펫토피아동물병원,False,True,False,False,False,False
80325,광교산동물병원,False,True,False,False,False,False
80326,광주 동물보호소,False,False,True,False,False,False
80327,광주 동물보호소,False,False,True,False,False,False
80328,광주 동물보호소,False,False,True,False,False,False
80329,제니스동물병원,False,True,False,False,False,False

In [10]:
df1.to_csv('test_df1-1.csv',encoding='euc-kr')

In [ ]:
# df1['orgNm'][df1['orgNm'].str.contains('서울특별시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경기도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('강원도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경상남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('경상북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('전라남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('전라북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('충청남도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('충청북도')==True]
# df1['orgNm'][df1['orgNm'].str.contains('울산광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('부산광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('대전광역시')==True]
# df1['orgNm'][df1['orgNm'].str.contains('제주특별자치도')==True]
#df1['orgNm'].unique()

In [ ]:
df1['orgNm'].str.contains('서울특별시').sum()

In [ ]:
df1['orgNm'].str.contains('경기도').sum()

In [ ]:
df1['orgNm'].str.contains('강원도').sum()

In [ ]:
df1['orgNm'].str.contains('경상남도').sum()

In [ ]:
df1['orgNm'].str.contains('경상북도').sum()

In [ ]:
df1['orgNm'].str.contains('전라남도').sum()

In [ ]:
df1['orgNm'].str.contains('전라북도').sum()

In [ ]:
df1['orgNm'].str.contains('충청남도').sum()

In [ ]:
df1['orgNm'].str.contains('충청북도').sum()

In [ ]:
df1['orgNm'].str.contains('울산광역시').sum()

In [ ]:
df1['orgNm'].str.contains('부산광역시').sum()

In [ ]:
df1['orgNm'].str.contains('대전광역시').sum()

In [ ]:
df1['orgNm'].str.contains('제주특별자치도').sum()

In [ ]:
df1['orgNm'].str.contains('세종특별자치시').sum()

In [ ]:
df1['orgNm'].str.contains('인천광역시').sum()

In [ ]:
df1['orgNm'].str.contains('광주광역시').sum()

In [ ]:
df1['orgNm'].str.contains('대구광역시').sum()

### KindCd, happenDt, happenPlace, colorCd

### Kind Cd

In [ ]:
df1['kindCd'].head()

In [ ]:
df1['kind'] = df1['kindCd'].str.extract('([가-힣]+)\]', expand=False) # 한글 정규식
df1['kind'].head()

In [ ]:
kind_mapping = {'개': 0, '고양이':1, '기타축종':2}
df1['kind'] = df1['kind'].map(kind_mapping)

In [ ]:
df1['kind'].value_counts()

In [ ]:
df1['breed'] = df1['kindCd'].str.split('] ').str[1]

In [ ]:
df1['breed'].head()

In [ ]:
# breed = df1['breed'].value_counts()
# breed

### happenDt

In [ ]:
df1['happenDt']

In [ ]:
df1['happenDt'] = pd.to_datetime(df1['happenDt'], format='%Y%m%d')
# 8자리를 날짜형식으로 바꿈

In [ ]:
df1['happenDt'].head()

In [ ]:
# df['happenWd'] = df['happenDt'].dt.dayofweekday  # 요일을 숫자로 표현함 "0 = Sunday"
df1['happenWd'] = df1['happenDt'].dt.day_name()

In [ ]:
df1['happenWd'].head()

In [ ]:
df1['happenWd'].value_counts()

In [ ]:
df1['happenMth'] = pd.DatetimeIndex(df1['happenDt']).month
# 날짜에서 '월'값을 받음

In [ ]:
df1['happenMth'].value_counts()

### weight

In [ ]:
df1['weight(after)'].head()

In [ ]:
df1.loc[df1['weight(after)'] <= 3, 'size'] = '초소형'
df1.loc[(df1['weight(after)'] > 3 ) & (df1['weight(after)'] <=9 ), 'size'] = '소형'
df1.loc[(df1['weight(after)'] > 9 ) & (df1['weight(after)'] <=25 ), 'size'] = '중형'
df1.loc[df1['weight(after)'] > 25, 'size'] = '대형'

In [ ]:
df1['size'].head()

In [ ]:
df1.loc[df1['age(after)'] <= 1, 'age_u'] = '유견기'
df1.loc[(df1['age(after)'] > 1 ) & (df1['age(after)'] <= 9 ), 'age_u'] = '성견기'
df1.loc[df1['age(after)'] > 9, 'age_u'] = '노견기'

In [ ]:
df1['age_u'].head()

In [ ]:
df1.columns

In [38]:
df1.to_csv('lostAnimal_20180101_20181231_vol3.csv',encoding='euc-kr')